<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <elementGuidId>8a79e23b-4e94-4062-b256-e30470d22e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-log-in-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modal-log-in-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1510cb83-048b-47f5-9af5-98004d0ee5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-semibold rounded-md shadow-md p-2 transition ease-out duration-500 transform hover:-translate-y-0.5  hover:scale-110 hover:opacity-80 whitespace-nowrap bg-secondary text-white w-1/4 mr-4</value>
      <webElementGuid>bd39c487-ae57-497b-a929-0c24486a2573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-log-in-button</value>
      <webElementGuid>1472be72-37cf-409c-9701-924e938539bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ec0b3dc-7b05-43c0-8f8c-a8bebec71fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>2611e6d1-f3bb-4de5-a415-7222965fb9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-log-in-button&quot;)</value>
      <webElementGuid>74736718-933e-4acb-b452-e65e8bdeb0a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modal-log-in-button']</value>
      <webElementGuid>8d02db06-0bf6-4d30-af49-dae828c8a78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-modal']/span/button[2]</value>
      <webElementGuid>99b21ebe-73d2-414b-8563-42e0b305c22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>4c2285ce-8aaa-4977-aad4-479fd320a1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to the terms of service'])[1]/following::button[2]</value>
      <webElementGuid>cfdfa6c0-fd41-477b-a844-42bcb62a3cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'modal-log-in-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>4b6922df-4d9f-46d5-9b3f-d36f42bd0df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button[2]</value>
      <webElementGuid>634eeb7f-33f4-481d-85dc-32046aee5714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modal-log-in-button' and @type = 'button' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>ad741e90-f30f-4027-b2a7-61bc6cdc64e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
